### ISSUE TITLE
Nice to have - colour of badges for own positions

### ISSUE THREAD

**Issue by chmst** [joomla-projects/gsoc21_core-enhancements#2]
### Is your feature request related to a problem? Please describe.

When I am in backend, overview, I see the positions as badges. Guess which position in this list is not an official position for the template preview? 

![grafik](https://user-images.githubusercontent.com/1035262/122433498-95c9b380-cf96-11eb-9c61-940833658454.png)

### Describe the solution you'd like
Positions which are not in the preview schould have other colours in this list

### Additional context
Be aware of performance :)

**Comment by YatharthVyas** [comment]
I've understood the issue and I've come up with an approach for it:

Make a new controller method in com_modules/src/Model/PositionsModel.php

This new controller will require the template name to be passed as a parameter. It will then use this template name to find all positions that are present in the templateDetails.xml path of that respective template name and we can use this array of positions to check each badge position and determine if they are displayed in the active template or not.

Proposed Time: 2-3 Days

Performance Impact: An extra computation of O(m*k) 
where 
m = number of positions in the active template 
k = number of items displayed in the table (this will generally be a constant between 10, 25 or 50.. as per the dropdown selection)

**Comment by YatharthVyas** [comment]
I have a Question for this:

In the atum's templateDetails.xml file, the List of positions are:

![image](https://user-images.githubusercontent.com/53610833/122639270-a1dc7f00-d116-11eb-96a2-8aadafabed4d.png)

but these do not include positions like `cpanel-components` etc so I am missing out on a way to identify active positions

![image](https://user-images.githubusercontent.com/53610833/122639321-ca647900-d116-11eb-935b-67cd74b8f1ad.png)

**Comment by YatharthVyas** [comment]
I came up with a new logic for the Position Badge Color Feature. I would be glad if the mentors could verify this before I start implementing:

![image](https://user-images.githubusercontent.com/53610833/122890892-b6f91e00-d361-11eb-9608-569a8ecd8168.png)

My approach has a minor flaw: I am not checking the Module's position name with those position names that only belong to the template style that is used in the Menu where the module is placed. 

 <hr>

If I were to do overcome this flaw, it would have a significant performance impact as I would have to use a JOIN query for fetching the template name for each module (which would be 4 tables JOIN ie, `Module`, `Module_Menu`, `Menu`, and `Template_styles`)

And after all this, I would still have to compare the position of that module with the list of all positions from it's templateDetails.xml file

 <hr width="10%" >

`Module` Table gives us the module name, it's `published` flag, `id`, `client_id` and its `position` name.
`Module_Menu` Table gives us the mapping between a `module_id` and it's `menu_id`
`Menu` Table maps the `menu_id` with the active `template_style_id` for it. (It is zero for default template)
`Template_styles` table has the template name mapped to the template_style_id and also contains the `home` flag for the default template.

<hr width="10%">

My goal of the above query is to map the Module's position name with it's template name. After which I will use the template name to find the list of all positions of it's templateDetails.xml file using this function from my PR https://github.com/joomla-projects/gsoc21_core-enhancements/blob/c0a4958d29cd8e6fbbf244f6abdd2541329d8901/administrator/components/com_modules/src/Model/ModulesModel.php#L505

**Comment by chmst** [comment]
Tested for cassiopeia - and it works fine. 

You could add now an information (toolTip) which says something like "valid position" or "non-valid position", then it is mor accessible for allusers who are colour blind or don't know what the colour means.

**Comment by chmst** [comment]
thanks!
