### ISSUE TITLE
Change Add Module Button to a Plugin

### ISSUE THREAD

**Issue by YatharthVyas** [joomla-projects/gsoc21_core-enhancements#5]
### What needs to be fixed
Add Module button should be inserted by the means of a plugin instead of PHP code

### Why this should be fixed
For better 3PD supportability

### How would you fix it
Switch to a Plugin

### Side Effects expected
Hopefully None

**Comment by chmst** [comment]
Maybe .. if somone switches on / off  the parameter "show module button", this also should enable /disable the plugin.

**Comment by YatharthVyas** [comment]
> Maybe .. if somone switches on / off the parameter "show module button", this also should enable /disable the plugin.

Or could we remove the show module button option from the configuration to avoid confusion?

**Comment by chmst** [comment]
Yes, good idea.
There are several features in joomla which work like this.
